language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: almilo@almilo.es
  api_key:
    secure: VTmpMobTMIL4BHcAFXAr+MiRF00HXPRXcA7VaY2wXvVH0ugtd9pwNi8Q7Xu4zejbsrjzDwALXEdVQtSZXA5vM3MupOMHMUaQh61dEPzr24/D+OD84u6EIDSmlxQUK1H7XN8V/7hkxYFuVVTdl0dUEvyhLY2OTUFAI/rmYuOhCEBSVCNWC2+D4i8Rqu9V+TBNMnxKbmGbCxq+hrL0+dGh7Zkgr34naoVdtO9AzsTZp6pX+LVK7niT8hU/VWEozZxKjn6WkMVFl6yr672xc+QVkJDNGAUCiJJOO9xo4Snl9RD142LRsDGPWG6FnvRKEPt2kTzgRMnrPqUPDhf137Uhj555yEpidEidkSwfIib/FhUu4gz9FBnPcVmwHLe7DMqx7artenepRddyPiV7Lu8/FAZ1QPb1EjJKKUZb/n8RfPN1Y3j0/pSRiVGN/zbTUamuXiJS1JQ2UB9U3oMGcrT+x6bzegZ7G0sBhN7Mal1+OBtFcLgOvVXuld75pvY9X9Zn8keGm6y3TUIARA19I8i4xb6qbqfI7llvaXaKBisA5XVJmTVJL52H0UECR22XcsRVFUPM9joiuTjNy2j8YcNsYy6CnGi/rdepqnQpcX7h6dp5eRSGKzOkQakLsBNoJBmvCHv/M060NJTdrNa45cRb4egiIOAdTi+RwE8UtCuCl4Q=
  on:
    tags: true
    all_branches: true
